apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - name: default
        image: drone/drone:1.0.0
        env:
        - name: DRONE_KUBERNETES_ENABLED
          value: "true"
        - name: DRONE_KUBERNETES_NAMESPACE
          value: default
        - name: DRONE_GITHUB_SERVER
          value: https://github.com
        - name: DRONE_GITHUB_CLIENT_ID
          value: $DRONE_GITHUB_CLIENT_ID
        - name: DRONE_GITHUB_CLIENT_SECRET
          value: $DRONE_GITHUB_CLIENT_SECRET
        - name: DRONE_RPC_SECRET
          value: $DRONE_RPC_SECRET
        - name: DRONE_SERVER_HOST
          value: $DRONE_SERVER_HOST
        - name: DRONE_SERVER_PROTO
          value: http
        ports:
        - containerPort: 80
        - containerPort: 443
